### ISSUE TITLE
License Issue 확인요청

### ISSUE THREAD

**Issue by tcpip98** [innocia/smartPop#2]
안녕하세요. smartPop.js 적용을 고려 중인 1인입니다.

지금 확인되는 바로는, MIT와 GPL이 Dual License인데...
GPL이 적용되는게 사실인가요?

MIT와 GPL은 워낙 배타적이라, 사용해야 할지 말지 고민이 되네요...

License에 대한 명확한 내용이 추가되었으면 좋겠습니다.

**Comment by inidu2** [comment]
너무 오래된 방식이라 더 이상 개발 및 지원 안합니다
라이센스 상관없으니 필요하시면 마음대로 사용하셔도 됩니다
요즘 개발방식과는 좀 차이가 있지만 잘 사용하시면 꽤 쓸만 합니다

**Comment by tcpip98** [comment]
^^ 네~ 감사합니다~
